apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "join-github.fullname" . }}
  labels:
    {{- include "join-github.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "join-github.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "join-github.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # serviceAccountName created by the Cloud Platform environment
      serviceAccountName: cd-serviceaccount
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ADMIN_GITHUB_TOKEN
              value: {{ .Values.application.githubToken| quote }}
            - name: AUTH0_DOMAIN
              value: {{ .Values.application.auth0Domain | quote }}
            - name: AUTH0_CLIENT_ID
              value: {{ .Values.application.auth0ClientId | quote }}
            - name: AUTH0_CLIENT_SECRET
              value: {{ .Values.application.auth0ClientSecret | quote }}
            - name: APP_SECRET_KEY
              value: {{ .Values.application.appSecretKey | quote }}
            - name: FLASK_CONFIGURATION
              value: {{ .Values.application.environment | quote }}
            - name: FLASK_DEBUG
              value: {{ .Values.application.flaskDebug | quote }}
            - name: SEND_EMAIL_INVITES
              value: {{ .Values.application.sendEmailInvites | quote }}
            - name: MOJ_ORG_ENABLED
              value: {{ .Values.application.mojOrgEnabled | quote }}
            - name: MOJ_AS_ORG_ENABLED
              value: {{ .Values.application.mojASOrgEnabled | quote }}
            - name: MOJ_TEST_ORG_ENABLED
              value: {{ .Values.application.mojTestOrgEnabled | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
