apiVersion: v1
kind: Service
metadata:
  name: {{ include "join-github.fullname" . }}
  labels:
    {{- include "join-github.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4567
      name: https
  selector:
    {{- include "join-github.selectorLabels" . | nindent 4 }}
