apiVersion: apps/v1
kind: Deployment
metadata:
  name: operations-engineering-landing-page-poc-deployment
  labels:
    app: operations-engineering-landing-page-poc
spec:
  replicas: 0 # ⚠️ Please do not deploy this application - read the [Web Application Security Assessment](./docs/web-application-security-assessment.md) for more information.
  selector:
    matchLabels:
      app: operations-engineering-landing-page-poc
  template:
    metadata:
      labels:
        app: operations-engineering-landing-page-poc
    spec:
      containers:
        - name: operations-engineering-landing-page-poc
          image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
          ports:
            - containerPort: 4567
          env:
            - name: GH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ops-eng-landing-page-poc-token
                  key: GH_TOKEN
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: ops-eng-landing-page-poc-token
                  key: AUTH0_CLIENT_ID
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ops-eng-landing-page-poc-token
                  key: AUTH0_CLIENT_SECRET
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: ops-eng-landing-page-poc-token
                  key: AUTH0_DOMAIN                
            - name: APP_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ops-eng-landing-page-poc-token
                  key: APP_SECRET_KEY                      
            - name: FLASK_CONFIGURATION
              valueFrom:
                secretKeyRef:
                  name: ops-eng-landing-page-poc-token
                  key: FLASK_CONFIGURATION                      
